import os
import smtplib
import re
import sys
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.image import MIMEImage
from openai import OpenAI
from datetime import datetime
import json
import logging

# Setup logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# ============= LOAD SECRETS =============
HF_TOKEN = os.environ.get('HF_TOKEN')
EMAIL_ADDRESS = os.environ.get('EMAIL_ADDRESS')
EMAIL_PASSWORD = os.environ.get('EMAIL_PASSWORD')
TO_EMAIL = os.environ.get('TO_EMAIL')
TEST_MODE = os.environ.get('TEST_MODE', 'false') == 'true'

# Override TO_EMAIL if in test mode
if TEST_MODE and EMAIL_ADDRESS:
    TO_EMAIL = EMAIL_ADDRESS
    logger.info(f"🧪 TEST MODE: Sending email to {TO_EMAIL}")

# Validate secrets
if not all([HF_TOKEN, EMAIL_ADDRESS, EMAIL_PASSWORD, TO_EMAIL]):
    missing = []
    if not HF_TOKEN: missing.append('HF_TOKEN')
    if not EMAIL_ADDRESS: missing.append('EMAIL_ADDRESS')
    if not EMAIL_PASSWORD: missing.append('EMAIL_PASSWORD')
    if not TO_EMAIL: missing.append('TO_EMAIL')
    logger.error(f"❌ Missing secrets: {', '.join(missing)}")
    sys.exit(1)

logger.info("✅ All secrets loaded successfully")

# ============= INITIALIZE DeepSeek AI =============
logger.info("🤖 Initializing DeepSeek R1 model via Hugging Face...")

client = OpenAI(
    base_url="https://router.huggingface.co/v1",
    api_key=HF_TOKEN,
)

# ============= SSC ASO SALARY DATA =============
salary_data = """
Government of India  
Assistant Section Officer (ASO)  

Employee Name: Abhishek Kumar  
Designation: Assistant Section Officer  

| Particulars    | Amount (₹) |
|---|---|
| Basic Pay:    | ₹85,000   |
| Dearness Allowance (DA):    | ₹1,000    |
| House Rent Allowance (HRA):    | ₹500    |
| Transport Allowance (TA):    | ₹12,000   |
| Other Allowances:    | ₹15,200   |
| Gross Salary:    | ₹1,13,700 |

Deductions:
- Income Tax: ₹1,200  
- Provident Fund: ₹30,000  
Total Deductions: ₹31,200  

Net In-Hand Salary: ₹82,500  

Stop Dreaming. Start Preparing. This Salary Will Be Yours Soon.
"""

def generate_html_with_deepseek():
    """Generate HTML email content using DeepSeek R1"""
    
    logger.info("📝 Sending request to DeepSeek R1 model...")
    
    prompt_message = f"""You are an expert email designer and motivational coach for SSC exam aspirants. 
Create a beautifully formatted HTML email about SSC ASO salary.

SALARY DATA:
{salary_data}

STRICT RULES:
1. Output ONLY valid HTML code. Do NOT use markdown like ```html or ```.
2. Use professional inline CSS with modern design (gradients, shadows, rounded corners).
3. Create a visually appealing email with:
   - Header with Government of India branding
   - Employee details section
   - Salary table with alternating row colors
   - Deductions section
   - Net salary highlight box
   - Motivational message with "Stop Dreaming. Start Preparing."
   - Call-to-action button for preparation
   - Benefits of SSC ASO job
   - Footer with date and motivational quote
4. Use colors: saffron (#FF9933), white (#FFFFFF), green (#138808) for Indian flag theme
5. Make it mobile-responsive
6. Add emojis for better visual appeal (💰, 📚, 🎯, 🏆, 💼)
7. Include current date: {datetime.now().strftime('%B %d, %Y')}
8. Add a section explaining why SSC ASO is a dream job
9. Add a note: "This email was generated by DeepSeek R1 AI for SSC aspirants"

The email should inspire SSC aspirants to work hard for this position.
"""

    try:
        # Call DeepSeek R1 model
        completion = client.chat.completions.create(
            model="deepseek-ai/DeepSeek-R1",
            messages=[
                {
                    "role": "system",
                    "content": "You are an expert HTML email designer specializing in government job exam motivation."
                },
                {
                    "role": "user",
                    "content": prompt_message
                }
            ],
            temperature=0.7,
            max_tokens=4000,
            timeout=60  # 60 seconds timeout
        )
        
        # Extract AI response
        ai_response = completion.choices[0].message.content
        
        # Remove DeepSeek's <think> tags if present
        html_content = re.sub(r'<think>.*?</think>', '', ai_response, flags=re.DOTALL).strip()
        
        # Remove markdown code blocks if AI wraps them
        html_content = html_content.replace('```html', '').replace('```', '').strip()
        
        # Save HTML for debugging
        with open('generated_email.html', 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        logger.info("✅ HTML email generated successfully by DeepSeek R1!")
        return html_content
        
    except Exception as e:
        logger.error(f"⚠️ Error calling DeepSeek R1: {e}")
        logger.info("🔄 Using fallback HTML template...")
        return get_fallback_html()

def get_fallback_html():
    """Fallback HTML template if DeepSeek fails"""
    
    return f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>SSC ASO Salary Details</title>
        <style>
            body {{
                font-family: 'Segoe UI', Arial, sans-serif;
                margin: 0;
                padding: 0;
                background: linear-gradient(135deg, #FF9933 0%, #FFFFFF 50%, #138808 100%);
            }}
            .container {{
                max-width: 600px;
                margin: 20px auto;
                background: white;
                border-radius: 15px;
                overflow: hidden;
                box-shadow: 0 10px 40px rgba(0,0,0,0.2);
            }}
            .header {{
                background: linear-gradient(135deg, #FF9933 0%, #FF6B35 100%);
                color: white;
                padding: 30px;
                text-align: center;
            }}
            .header h1 {{ margin: 0; font-size: 28px; }}
            .content {{ padding: 30px; }}
            .salary-table {{
                width: 100%;
                border-collapse: collapse;
                margin: 20px 0;
            }}
            .salary-table td {{
                padding: 12px;
                border-bottom: 1px solid #e0e0e0;
            }}
            .salary-table tr:nth-child(even) {{
                background-color: #f8f9fa;
            }}
            .net-salary {{
                background: linear-gradient(135deg, #138808 0%, #0D5C0D 100%);
                color: white;
                padding: 20px;
                text-align: center;
                border-radius: 10px;
                margin: 20px 0;
            }}
            .net-salary h2 {{ margin: 0; font-size: 36px; }}
            .motivation {{
                background: linear-gradient(135deg, #FF9933 0%, #FF6B35 100%);
                color: white;
                text-align: center;
                padding: 30px;
                border-radius: 10px;
                margin: 20px 0;
            }}
            .cta-button {{
                display: inline-block;
                background: #138808;
                color: white;
                padding: 12px 30px;
                text-decoration: none;
                border-radius: 25px;
                font-weight: bold;
                margin-top: 15px;
            }}
            .footer {{
                background: #f8f9fa;
                padding: 20px;
                text-align: center;
                color: #666;
                font-size: 12px;
            }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>🏛️ Government of India</h1>
                <p>Assistant Section Officer (ASO) - Salary Breakdown</p>
                <p>{datetime.now().strftime('%B %d, %Y')}</p>
            </div>
            <div class="content">
                <h3>👤 Employee: Abhishek Kumar</h3>
                <table class="salary-table">
                    <tr><td><strong>Basic Pay:</strong></td><td>₹85,000</td></tr>
                    <tr><td><strong>Dearness Allowance (DA):</strong></td><td>₹1,000</td></tr>
                    <tr><td><strong>House Rent Allowance (HRA):</strong></td><td>₹500</td></tr>
                    <tr><td><strong>Transport Allowance (TA):</strong></td><td>₹12,000</td></tr>
                    <tr><td><strong>Other Allowances:</strong></td><td>₹15,200</td></tr>
                    <tr style="border-top: 2px solid #333;">
                        <td><strong>Gross Salary:</strong></td>
                        <td><strong>₹1,13,700</strong></td>
                    </tr>
                </table>
                <div class="net-salary">
                    <p>💰 NET IN-HAND SALARY</p>
                    <h2>₹82,500</h2>
                    <p>per month</p>
                </div>
                <div class="motivation">
                    <h2>🎯 Stop Dreaming.</h2>
                    <h2>📚 Start Preparing.</h2>
                    <p style="font-size: 20px;">This Salary Will Be Yours Soon!</p>
                    <a href="#" class="cta-button">Begin Your Journey →</a>
                </div>
                <p style="text-align: center; margin-top: 20px; color: #666;">
                    🤖 Generated by DeepSeek R1 AI for SSC aspirants
                </p>
            </div>
            <div class="footer">
                <p>🌟 Dream it. Achieve it. 🌟</p>
                <p>Stay motivated, stay consistent!</p>
                <p>© {datetime.now().year} SSC Exam Preparation Guide</p>
            </div>
        </div>
    </body>
    </html>
    """

def send_email(html_content, image_path='image.jpg'):
    """Send email with HTML content and optional image"""
    
    logger.info(f"📧 Preparing email to {TO_EMAIL}...")
    
    msg = MIMEMultipart('related')
    msg['From'] = EMAIL_ADDRESS
    msg['To'] = TO_EMAIL
    msg['Subject'] = f"💰 SSC ASO Salary {datetime.now().strftime('%d %b %Y')} - Your Dream Govt Job 🇮🇳"
    
    # Attach HTML content
    msg_alternative = MIMEMultipart('alternative')
    msg.attach(msg_alternative)
    msg_alternative.attach(MIMEText(html_content, 'html'))
    
    # Attach image if exists
    if os.path.exists(image_path):
        try:
            with open(image_path, 'rb') as img_file:
                img = MIMEImage(img_file.read(), name=os.path.basename(image_path))
                img.add_header('Content-ID', '<salary_image>')
                img.add_header('Content-Disposition', 'inline', filename=os.path.basename(image_path))
                msg.attach(img)
                logger.info(f"✅ Image '{image_path}' attached!")
        except Exception as e:
            logger.warning(f"⚠️ Could not attach image: {e}")
    else:
        logger.info(f"ℹ️ Image '{image_path}' not found, sending text-only email")
    
    # Send email
    try:
        logger.info("📤 Connecting to Gmail SMTP...")
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(EMAIL_ADDRESS, EMAIL_PASSWORD)
        server.send_message(msg)
        server.quit()
        
        logger.info("=" * 50)
        logger.info("✅ EMAIL SENT SUCCESSFULLY!")
        logger.info(f"📨 To: {TO_EMAIL}")
        logger.info(f"📋 Subject: SSC ASO Salary - {datetime.now().strftime('%d %b %Y')}")
        logger.info("=" * 50)
        return True
        
    except Exception as e:
        logger.error(f"❌ Failed to send email: {e}")
        return False

# ============= MAIN EXECUTION =============
if __name__ == "__main__":
    print("=" * 60)
    print("🇮🇳 SSC ASO SALARY EMAIL GENERATOR with DeepSeek R1 🤖")
    print(f"🕐 Run at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 60)
    
    # Generate HTML content
    html_content = generate_html_with_deepseek()
    
    # Send email
    success = send_email(html_content, 'image.jpg')
    
    # Exit with appropriate code
    sys.exit(0 if success else 1)
